// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAQcCh6sHv1VYQMjaaJ3AA_CHpzQFi6hk',
    appId: '1:730675446643:web:6b48508396064db2c73b06',
    messagingSenderId: '730675446643',
    projectId: 'sales-bet-project',
    authDomain: 'sales-bet-project.firebaseapp.com',
    storageBucket: 'sales-bet-project.firebasestorage.app',
    measurementId: 'G-TJHZ03XK2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4gWXV-IHtOuVDANazopZEj7BjO7lnd8',
    appId: '1:730675446643:android:83b5587694403296c73b06',
    messagingSenderId: '730675446643',
    projectId: 'sales-bet-project',
    storageBucket: 'sales-bet-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn9DYnFG8tO9m8mL1AHlxYCCHo8XJ_VPM',
    appId: '1:730675446643:ios:256bf039e2b10e02c73b06',
    messagingSenderId: '730675446643',
    projectId: 'sales-bet-project',
    storageBucket: 'sales-bet-project.firebasestorage.app',
    iosBundleId: 'com.example.salesBetProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn9DYnFG8tO9m8mL1AHlxYCCHo8XJ_VPM',
    appId: '1:730675446643:ios:256bf039e2b10e02c73b06',
    messagingSenderId: '730675446643',
    projectId: 'sales-bet-project',
    storageBucket: 'sales-bet-project.firebasestorage.app',
    iosBundleId: 'com.example.salesBetProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAQcCh6sHv1VYQMjaaJ3AA_CHpzQFi6hk',
    appId: '1:730675446643:web:4ff8ec41a804256bc73b06',
    messagingSenderId: '730675446643',
    projectId: 'sales-bet-project',
    authDomain: 'sales-bet-project.firebaseapp.com',
    storageBucket: 'sales-bet-project.firebasestorage.app',
    measurementId: 'G-XL1MZ3WGQT',
  );
}
